
name: Build ImmortalWrt (23.05 x86_64 J4125 Slim)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          repository: immortalwrt/immortalwrt
          ref: openwrt-23.05

      - name: Set up build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
            gcc git libelf-dev libncurses5-dev libncursesw5-dev libssl-dev \
            python3 unzip wget zlib1g-dev rsync

      - name: Inject custom .config
        run: |
          cat > .config <<'EOF'
          # ==== Target: x86_64 / Generic ====
CONFIG_TARGET_x86=y
CONFIG_TARGET_x86_64=y
CONFIG_TARGET_x86_64_DEVICE_generic=y

# ==== Kernel ====
CONFIG_LINUX_5_15=y

# ==== Image format ====
CONFIG_TARGET_ROOTFS_SQUASHFS=y
CONFIG_TARGET_IMAGES_GZIP=y
CONFIG_EFI_IMAGES=y
CONFIG_GRUB_IMAGES=y

# ==== Base system ====
CONFIG_PACKAGE_base-files=y
CONFIG_PACKAGE_busybox=y
CONFIG_PACKAGE_ca-bundle=y
CONFIG_PACKAGE_ca-certificates=y
CONFIG_PACKAGE_coreutils=y
CONFIG_PACKAGE_coreutils-nohup=y
CONFIG_PACKAGE_htop=y
CONFIG_PACKAGE_bash=y
CONFIG_PACKAGE_vim=y
CONFIG_PACKAGE_curl=y
CONFIG_PACKAGE_wget-ssl=y

# ==== Networking core ====
CONFIG_PACKAGE_dnsmasq-full=y
CONFIG_PACKAGE_ip-full=y
CONFIG_PACKAGE_iptables=y
CONFIG_PACKAGE_ip6tables=y
CONFIG_PACKAGE_ipset=y
CONFIG_PACKAGE_ppp=y
CONFIG_PACKAGE_pppoe=y
CONFIG_PACKAGE_odhcp6c=y
CONFIG_PACKAGE_odhcpd-ipv6only=y

# ==== Drivers (J4125 / Intel NICs) ====
CONFIG_PACKAGE_kmod-igb=y
CONFIG_PACKAGE_kmod-igc=y
CONFIG_PACKAGE_kmod-e1000e=y
CONFIG_PACKAGE_kmod-r8169=y

# ==== TUN / Netfilter ====
CONFIG_PACKAGE_kmod-tun=y
CONFIG_PACKAGE_kmod-ipt-nat=y
CONFIG_PACKAGE_kmod-ipt-tproxy=y
CONFIG_PACKAGE_iptables-mod-tproxy=y
CONFIG_PACKAGE_iptables-mod-extra=y
CONFIG_PACKAGE_kmod-nft-offload=y
CONFIG_PACKAGE_kmod-tcp-bbr=y

# ==== Filesystems & storage ====
CONFIG_PACKAGE_block-mount=y
CONFIG_PACKAGE_blkid=y
CONFIG_PACKAGE_fdisk=y
CONFIG_PACKAGE_kmod-usb-storage=y
CONFIG_PACKAGE_kmod-usb3=y
CONFIG_PACKAGE_kmod-fs-ext4=y
CONFIG_PACKAGE_kmod-fs-vfat=y
CONFIG_PACKAGE_kmod-fs-exfat=y

# ==== LuCI (web UI) ====
CONFIG_PACKAGE_luci=y
CONFIG_PACKAGE_luci-ssl=y
CONFIG_PACKAGE_luci-compat=y
CONFIG_PACKAGE_luci-theme-bootstrap=y
CONFIG_PACKAGE_luci-app-opkg=y
CONFIG_PACKAGE_luci-app-firewall=y

# ==== Essentials for your use-case ====
# OpenClash for proxy + streaming unlock
CONFIG_PACKAGE_luci-app-openclash=y
# SmartDNS for fast/resolved DNS, lighter than full AdGuardHome
CONFIG_PACKAGE_luci-app-smartdns=y
CONFIG_PACKAGE_smartdns=y
# UPnP for PS5/NAT
CONFIG_PACKAGE_luci-app-upnp=y
CONFIG_PACKAGE_miniupnpd=y
# DDNS (optional but small)
CONFIG_PACKAGE_luci-app-ddns=y
CONFIG_PACKAGE_ddns-scripts=y
CONFIG_PACKAGE_ddns-scripts-services=y

# ==== Optional (tiny) tools ====
CONFIG_PACKAGE_bind-dig=y
CONFIG_PACKAGE_ethtool=y

# ==== IPv6 ====
CONFIG_IPV6=y
CONFIG_PACKAGE_ip6tables=y
CONFIG_PACKAGE_odhcp6c=y
CONFIG_PACKAGE_odhcpd-ipv6only=y

          EOF

      - name: Update & install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build
        run: |
          make defconfig
          make download -j$(nproc) || true
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-x86_64-23.05-slim
          path: bin/targets/x86/64/*
